site_name: HEMY MOTES

site_description: HEMY's Personal Notes

repo_url: https://github.com/hemy08/hemynotes

copyright: Copyright &copy; 2021-2029 HEMY08



theme:
  favicon: themes/images/lvye.png
  feature:
    tabs: 'true'
  features:
  - navigation.tracking
  - navigation.tabs
  - navigation.indexes
  - navigation.prune
  - navigation.top
  - toc.follow
  - header.autohide
  - search.share
  - search.suggest
  - search.highlight
  icon:
    admonition:
      abstract: octicons/checklist-16
      bug: octicons/bug-16
      danger: octicons/zap-16
      example: octicons/beaker-16
      failure: octicons/x-circle-16
      info: octicons/info-16
      note: octicons/tag-16
      question: octicons/question-16
      quote: octicons/quote-16
      success: octicons/check-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16
    logo: material/library
  language: zh
  name: material
  palette:
    scheme: default


plugins:
  search:
    lang:
    - en
    - ru
    - zh
    - ja
    separator: '[\s\u200b\-]'


extra:
  generator: false
  search:
    language: en, jp, zh
  social:
  - icon: fontawesome/solid/chalkboard
    link: https://www.w3cschool.cn/
    name: 编程狮W3C
  - icon: fontawesome/solid/dove
    link: https://www.runoob.com/
    name: 菜鸟教程
  - icon: fontawesome/solid/laptop-code
    link: https://leetcode.cn/
    name: 力扣
  - icon: fontawesome/solid/file-code
    link: http://www.verysource.com/
    name: 源码查询
  - icon: fontawesome/solid/toolbox
    link: https://c.runoob.com/
    name: 菜鸟工具
  - icon: fontawesome/solid/pen-nib
    link: https://hdesign.ucd.huawei.com/assemble/designcloud
    name: DesignCloud
  - icon: fontawesome/solid/at
    link: mailto:<zhaojunwei008@yeah.net>
    name: Email


extra_css:
- themes/css/custom.css
- themes/css/simpleLightbox.min.css
- themes/css/pied_piper.css
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css


extra_javascript:
- themes/js/custom.js
- themes/js/simpleLightbox.min.js
- themes/js/optionalConfig.js
- themes/js/mermaidloader.js
- themes/js/umlconvert.js
- themes/js/mathjax.js
- themes/js/katex.js
- https://unpkg.com/mermaid@10.0.2/dist/mermaid.esm.min.mjs
- https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.17.1/flowchart.min.js
- https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js
- https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.13.6/underscore-min.js
- https://unpkg.com/@mermaid-js/mermaid-mindmap@9.3.0/dist/mermaid-mindmap.esm.min.mjs
- https://unpkg.com/@markspec/markdown-it-plantuml@1.1.4/index.js
- https://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.28/webfontloader.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml-full.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-svg-full.js
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js


markdown_extensions:
- admonition
- footnotes
- meta
- def_list
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.snippets
- tables
- pymdownx.mark
- pymdownx.inlinehilite
- pymdownx.smartsymbols
- pymdownx.tilde
- attr_list
- md_in_html
- pymdownx.arithmatex:
    generic: true
- pymdownx.emoji:
    emoji_generator: !!python/name:materialx.emoji.to_svg
    emoji_index: !!python/name:materialx.emoji.twemoji
- pymdownx.highlight:
    anchor_linenums: true
    auto_title: true
    line_spans: __span
    linenums: true
    pygments_lang_class: true
- pymdownx.magiclink:
    repo: mkdocs-material
    repo_url_shorthand: true
    user: squidfunk
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- codehilite:
    guess_lang: false
    linenums: false
- toc:
    permalink: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_png
- pymdownx.superfences:
    custom_fences:
    - class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
      name: mermaid
    - class: flow
      format: !!python/name:pymdownx.superfences.fence_code_format
      name: uml-flowchart
    - class: sequence
      format: !!python/name:pymdownx.superfences.fence_code_format
      name: sequence
    preserve_tabs: true

nav:
  - HOME: https://hemy08.github.io/hemynotes/
  - Windows:
    - mstsc副屏全屏显示: Windows/01-mstsc副屏全屏显示.md
    - 右键菜单添加新建记事本: Windows/02-右键菜单添加新建记事本.md
    - windows常用cmd命令: Windows/03-windows常用cmd命令.md
    - 让任务栏在屏幕左侧变窄: Windows/04-让任务栏在屏幕左侧变窄.md
    - 计算云鼠标飘的解决办法: Windows/05-计算云鼠标飘的解决办法.md
    - 鼠标右键菜单排序: Windows/06-鼠标右键菜单排序.md
    - windows.edb文件: Windows/07-windows.edb文件.md
    - 找到文件被哪个进程引用: Windows/08-找到文件被哪个进程引用.md
    - Win11修改bat默认打开方式: Windows/09-Win11修改bat默认打开方式.md
    - win11上临时文件清理: Windows/10-win11上临时文件清理.md
  - 百度: https://www.baidu.com
