site_name: HEMY MOTES

site_description: HEMY's Personal Notes

repo_url: https://github.com/hemy08/hemynotes

copyright: Copyright &copy; 2021-2029 HEMY08

theme:
  favicon: themes/images/lvye.png
  feature:
    tabs: 'true'
  features:
  - announce.dismiss
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - content.tabs.link
  - navigation.tracking
  - navigation.indexes
  - navigation.prune
  - navigation.top
  - navigation.tabs
  - toc.follow
  - header.autohide
  - search.share
  - search.suggest
  - search.highlight
  font:
    code: Roboto Mono
    text: Roboto
  icon:
    admonition:
      abstract: octicons/checklist-16
      bug: octicons/bug-16
      danger: octicons/zap-16
      example: octicons/beaker-16
      failure: octicons/x-circle-16
      info: octicons/info-16
      note: octicons/tag-16
      question: octicons/question-16
      quote: octicons/quote-16
      success: octicons/check-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16
    logo: material/library
  language: zh
  name: material
  palette:
    scheme: default

plugins:
  search:
    lang:
    - en
    - ru
    - zh
    - ja
    separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

extra:
  generator: false
  search:
    language: en, jp, zh
  social:
  - icon: fontawesome/solid/chalkboard
    link: https://www.w3cschool.cn/
    name: 编程狮W3C
  - icon: fontawesome/solid/dove
    link: https://www.runoob.com/
    name: 菜鸟教程
  - icon: fontawesome/solid/laptop-code
    link: https://leetcode.cn/
    name: 力扣
  - icon: fontawesome/solid/file-code
    link: http://www.verysource.com/
    name: 源码查询
  - icon: fontawesome/solid/toolbox
    link: https://c.runoob.com/
    name: 菜鸟工具
  - icon: fontawesome/solid/pen-nib
    link: https://github.com/hemy08/hemynotes/issues
    name: issues
  - icon: fontawesome/solid/at
    link: mailto:<zhaojunwei008@yeah.net>
    name: Email

extra_css:
- themes/css/custom.css
- themes/css/simpleLightbox.min.css
- themes/css/pied_piper.css
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css

extra_javascript:
- themes/js/custom.js
- themes/js/simpleLightbox.min.js
- themes/js/optionalConfig.js
- themes/js/mermaidloader.js
- themes/js/umlconvert.js
- themes/js/mathjax.js
- themes/js/katex.js
- https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
- https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.17.1/flowchart.min.js
- https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js
- https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.13.6/underscore-min.js
- https://cdn.jsdelivr.net/npm/@mermaid-js/mermaid-mindmap@9.3.0/dist/diagram-definition.0faef4c2.min.js
- https://cdn.jsdelivr.net/npm/markdown-it-plantuml@1.4.1/index.min.js
- https://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.28/webfontloader.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml-full.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-svg-full.js
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js

markdown_extensions:
- abbr
- attr_list
- admonition
- footnotes
- meta
- def_list
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.snippets
- tables
- pymdownx.mark
- pymdownx.inlinehilite
- pymdownx.smartsymbols
- pymdownx.tilde
- attr_list
- md_in_html
- pymdownx.arithmatex:
    generic: true
- pymdownx.emoji:
    emoji_generator: !!python/name:materialx.emoji.to_svg
    emoji_index: !!python/name:materialx.emoji.twemoji
- pymdownx.highlight:
    anchor_linenums: true
    auto_title: true
    line_spans: __span
    linenums: true
    pygments_lang_class: true
- pymdownx.magiclink:
    repo: mkdocs-material
    repo_url_shorthand: true
    user: squidfunk
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- codehilite:
    guess_lang: false
    linenums: false
- toc:
    permalink: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_png
- pymdownx.superfences:
    custom_fences:
    - class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
      name: mermaid
    - class: flow
      format: !!python/name:pymdownx.superfences.fence_code_format
      name: uml-flowchart
    - class: sequence
      format: !!python/name:pymdownx.superfences.fence_code_format
      name: sequence
    preserve_tabs: true


nav:
  - HOME: https://hemy08.github.io/hemynotes/
  - 计算机:
    - 导读: 010-计算机/000_导读.md
    - 计算机基础:
      - 导读: 010-计算机/010_计算机基础/000_导读.md
      - 计算机概述:
        - 导读: 010-计算机/010_计算机基础/000_计算机概述/000_导读.md
        - 计算机发展历程:
          - 导读: 010-计算机/010_计算机基础/000_计算机概述/010_计算机发展历程/000-导读.md
          - 史前计算机时代: 010-计算机/010_计算机基础/000_计算机概述/010_计算机发展历程/001-史前计算机时代.md
          - 机械式计算机时代: 010-计算机/010_计算机基础/000_计算机概述/010_计算机发展历程/002-机械式计算机时代.md
          - 电子管计算机: 010-计算机/010_计算机基础/000_计算机概述/010_计算机发展历程/003-电子管计算机.md
          - 晶体管计算机: 010-计算机/010_计算机基础/000_计算机概述/010_计算机发展历程/004-晶体管计算机.md
          - 集成电路计算机: 010-计算机/010_计算机基础/000_计算机概述/010_计算机发展历程/005-集成电路计算机.md
          - 超大规模集成电路计算机: 010-计算机/010_计算机基础/000_计算机概述/010_计算机发展历程/006-超大规模集成电路计算机.md
          - 智能计算机: 010-计算机/010_计算机基础/000_计算机概述/010_计算机发展历程/007-智能计算机.md
          - 计算机语言发展史: 010-计算机/010_计算机基础/000_计算机概述/010_计算机发展历程/008-计算机语言发展史.md
        - 计算机的分类与发展方向:
          - 导读: 010-计算机/010_计算机基础/000_计算机概述/020_计算机的分类与发展方向/000-导读.md
          - 电子模拟计算机: 010-计算机/010_计算机基础/000_计算机概述/020_计算机的分类与发展方向/001-电子模拟计算机.md
          - 电子数字计算机: 010-计算机/010_计算机基础/000_计算机概述/020_计算机的分类与发展方向/002-电子数字计算机.md
          - Flynn分类法: 010-计算机/010_计算机基础/000_计算机概述/020_计算机的分类与发展方向/003-Flynn分类法.md
          - 生物计算机: 010-计算机/010_计算机基础/000_计算机概述/020_计算机的分类与发展方向/008-生物计算机.md
          - 分子计算机: 010-计算机/010_计算机基础/000_计算机概述/020_计算机的分类与发展方向/009-分子计算机.md
          - 量子计算机: 010-计算机/010_计算机基础/000_计算机概述/020_计算机的分类与发展方向/010-量子计算机.md
          - 光子计算机: 010-计算机/010_计算机基础/000_计算机概述/020_计算机的分类与发展方向/011-光子计算机.md
          - 纳米计算机: 010-计算机/010_计算机基础/000_计算机概述/020_计算机的分类与发展方向/012-纳米计算机.md
        - 计算机系统的组成:
          - 导读: 010-计算机/010_计算机基础/000_计算机概述/030_计算机系统的组成/000-导读.md
          - 控制器: 010-计算机/010_计算机基础/000_计算机概述/030_计算机系统的组成/001-控制器.md
          - 存储器: 010-计算机/010_计算机基础/000_计算机概述/030_计算机系统的组成/002-存储器.md
          - 运算器: 010-计算机/010_计算机基础/000_计算机概述/030_计算机系统的组成/003-运算器.md
          - 输入设备: 010-计算机/010_计算机基础/000_计算机概述/030_计算机系统的组成/004-输入设备.md
          - 输出设备: 010-计算机/010_计算机基础/000_计算机概述/030_计算机系统的组成/006-输出设备.md
          - 计算机存储器: 010-计算机/010_计算机基础/000_计算机概述/030_计算机系统的组成/012-计算机存储器.md
        - 计算机工作过程:
          - 导读: 010-计算机/010_计算机基础/000_计算机概述/040_计算机工作过程/000-导读.md
        - 计算机软件系统:
          - 导读: 010-计算机/010_计算机基础/000_计算机概述/050_计算机软件系统/000-导读.md
        - 计算机编程语言:
          - 导读: 010-计算机/010_计算机基础/000_计算机概述/060_计算机编程语言/000-导读.md
        - 计算机系统的层次结构:
          - 导读: 010-计算机/010_计算机基础/000_计算机概述/070_计算机系统的层次结构/000-导读.md
        - 冯诺依曼计算机:
          - 导读: 010-计算机/010_计算机基础/000_计算机概述/080_冯诺依曼计算机/000-导读.md
        - 存储器:
          - 导读: 010-计算机/010_计算机基础/000_计算机概述/090_存储器/000-导读.md
        - 计算机性能指标:
          - 导读: 010-计算机/010_计算机基础/000_计算机概述/100_计算机性能指标/000-导读.md
      - 数据的表示和运算:
        - 导读: 010-计算机/010_计算机基础/010_数据的表示和运算/000-导读.md
      - 存储系统:
        - 导读: 010-计算机/010_计算机基础/020_存储系统/000-导读.md
      - 指令系统:
        - 导读: 010-计算机/010_计算机基础/030_指令系统/000-导读.md
      - 中央处理器:
        - 导读: 010-计算机/010_计算机基础/040_中央处理器/000-导读.md
      - 总线:
        - 导读: 010-计算机/010_计算机基础/050_总线/000-导读.md
    - 计算机组成原理:
      - 导读: 010-计算机/020_计算机组成原理/000-导读.md
    - 计算机操作系统:
      - 导读: 010-计算机/030_计算机操作系统/000-导读.md
    - 计算机网络:
      - 计算机网络: 010-计算机/040_计算机网络/计算机网络.md
    - 文件系统:
      - 导读: 010-计算机/050_文件系统/000-导读.md
      - 文件管理:
        - 导读: 010-计算机/050_文件系统/070_文件管理/000-导读.md
    - 输入输出系统:
      - 导读: 010-计算机/060_输入输出系统/000-导读.md
    - 进程与线程:
      - 导读: 010-计算机/070_进程与线程/000-导读.md
    - 数据库系统:
      - 导读: 010-计算机/080_数据库系统/000-导读.md
  - 操作系统:
    - 导读: 020-操作系统/000-导读.md
    - Windows系统:
      - 导读: 020-操作系统/010-Windows系统/000-导读.md
      - mstsc副屏全屏显示: 020-操作系统/010-Windows系统/01-mstsc副屏全屏显示.md
      - 右键菜单添加新建记事本: 020-操作系统/010-Windows系统/02-右键菜单添加新建记事本.md
      - windows常用cmd命令: 020-操作系统/010-Windows系统/03-windows常用cmd命令.md
      - 让任务栏在屏幕左侧变窄: 020-操作系统/010-Windows系统/04-让任务栏在屏幕左侧变窄.md
      - 鼠标飘的解决办法: 020-操作系统/010-Windows系统/05-鼠标飘的解决办法.md
      - 鼠标右键菜单排序: 020-操作系统/010-Windows系统/06-鼠标右键菜单排序.md
      - windows.edb文件: 020-操作系统/010-Windows系统/07-windows.edb文件.md
      - 找到文件被哪个进程引用: 020-操作系统/010-Windows系统/08-找到文件被哪个进程引用.md
      - Win11修改bat默认打开方式: 020-操作系统/010-Windows系统/09-Win11修改bat默认打开方式.md
      - win11上临时文件清理: 020-操作系统/010-Windows系统/10-win11上临时文件清理.md
    - Linux系统:
      - 导读: 020-操作系统/020-Linux系统/000-导读.md
      - linux系统Errorid的含义: 020-操作系统/020-Linux系统/06-linux系统Errorid的含义.md
      - linux系统文件权限解读: 020-操作系统/020-Linux系统/07-linux系统文件权限解读.md
      - openssl生成证书步骤: 020-操作系统/020-Linux系统/08-openssl生成证书步骤.md
      - zypper-help: 020-操作系统/020-Linux系统/16-zypper-help.md
      - 压缩与解压相关命令:
        - tar命令: 020-操作系统/020-Linux系统/压缩与解压相关命令/12-tar命令.md
        - zip命令: 020-操作系统/020-Linux系统/压缩与解压相关命令/15-zip命令.md
      - 目录与文件操作命令:
        - grep命令: 020-操作系统/020-Linux系统/目录与文件操作命令/03-grep命令.md
        - rsync命令: 020-操作系统/020-Linux系统/目录与文件操作命令/09-rsync命令.md
        - sed命令: 020-操作系统/020-Linux系统/目录与文件操作命令/10-sed命令.md
        - sync命令: 020-操作系统/020-Linux系统/目录与文件操作命令/11-sync命令.md
        - diff命令文件内容比较: 020-操作系统/020-Linux系统/目录与文件操作命令/18-diff命令文件内容比较.md
        - cp复制命令: 020-操作系统/020-Linux系统/目录与文件操作命令/cp复制命令.md
        - setfacl设置文件访问控制列表: 020-操作系统/020-Linux系统/目录与文件操作命令/setfacl设置文件访问控制列表.md
      - 网络相关命令:
        - curl命令:
          - curl-命令参数: 020-操作系统/020-Linux系统/网络相关命令/curl命令/curl-命令参数.md
          - curl-常用实例: 020-操作系统/020-Linux系统/网络相关命令/curl命令/curl-常用实例.md
          - curl-错误码解释: 020-操作系统/020-Linux系统/网络相关命令/curl命令/curl-错误码解释.md
        - IP命令详解:
          - ip address命令详解: 020-操作系统/020-Linux系统/网络相关命令/IP命令详解/ip address命令详解.md
          - ip link命令详解: 020-操作系统/020-Linux系统/网络相关命令/IP命令详解/ip link命令详解.md
          - ip route命令详解: 020-操作系统/020-Linux系统/网络相关命令/IP命令详解/ip route命令详解.md
          - ip rule命令详解: 020-操作系统/020-Linux系统/网络相关命令/IP命令详解/ip rule命令详解.md
          - ip命令格式详解: 020-操作系统/020-Linux系统/网络相关命令/IP命令详解/ip命令格式详解.md
        - nslookup命令详解: 020-操作系统/020-Linux系统/网络相关命令/nslookup命令详解.md
        - tcpdump命令: 020-操作系统/020-Linux系统/网络相关命令/tcpdump命令.md
        - 进程端口相关:
          - fuser命令: 020-操作系统/020-Linux系统/网络相关命令/进程端口相关/fuser命令.md
          - lsof命令: 020-操作系统/020-Linux系统/网络相关命令/进程端口相关/lsof命令.md
          - netstat命令详解: 020-操作系统/020-Linux系统/网络相关命令/进程端口相关/netstat命令详解.md
          - ss命令: 020-操作系统/020-Linux系统/网络相关命令/进程端口相关/ss命令.md
    - 嵌入式系统:
      - 导读: 020-操作系统/030-嵌入式系统/000-导读.md
  - 数据结构与算法:
    - 算法思想:
      - 滑动窗口: 030-数据结构与算法/算法思想/滑动窗口.md
  - 编程语言:
    - 导读: 040-编程语言/000-导读.md
  - 软件工程:
    - 导读: 050-软件工程/000-导读.md
    - 软件架构:
      - 导读: 050-软件工程/010-软件架构/000-导读.md
    - 软件设计:
      - 导读: 050-软件工程/020-软件设计/000-导读.md
    - 设计模式:
      - 导读: 050-软件工程/030-设计模式/000-导读.md
    - 软件建模:
      - 导读: 050-软件工程/040-软件建模/000-导读.md
    - 软件测试技术:
      - 导读: 050-软件工程/050-软件测试技术/000-导读.md
    - 系统设计:
      - 导读: 050-软件工程/060-系统设计/000-导读.md
    - 人工智能与识别:
      - 导读: 050-软件工程/070-人工智能与识别/000-导读.md
    - 嵌入式软件与应用:
      - 导读: 050-软件工程/080-嵌入式软件与应用/000-导读.md
    - 自动控制:
      - 导读: 050-软件工程/090-自动控制/000-导读.md
    - 分布式计算与网格计算:
      - 导读: 050-软件工程/100-分布式计算与网格计算/000-导读.md
    - 云计算技术:
      - 导读: 050-软件工程/110-云计算技术/000-导读.md
    - 大数据分析与处理:
      - 导读: 050-软件工程/120-大数据分析与处理/000-导读.md
  - 实用技能:
    - 导读: 060-实用技能/000-导读.md
  - 力扣题解:
    - 导读: 500-力扣题解/000-导读.md
    - 动态规划:
      - 买卖股票的最佳时机II: 500-力扣题解/动态规划/买卖股票的最佳时机II.md
      - 最长等差数列: 500-力扣题解/动态规划/最长等差数列.md
    - 双指针:
      - 接雨水: 500-力扣题解/双指针/接雨水.md
    - 堆栈相关:
      - 有效的括号: 500-力扣题解/堆栈相关/有效的括号.md
    - 字符串:
      - 字符串中的第一个唯一字符: 500-力扣题解/字符串/字符串中的第一个唯一字符.md
    - 数组和哈希:
      - 哈希:
        - 最长连续序列: 500-力扣题解/数组和哈希/哈希/最长连续序列.md
        - 有效的数独: 500-力扣题解/数组和哈希/哈希/有效的数独.md
      - 数组:
        - 下一个排列: 500-力扣题解/数组和哈希/数组/下一个排列.md
        - 两个数组的交集II: 500-力扣题解/数组和哈希/数组/两个数组的交集II.md
        - 删除排序数组中的重复项: 500-力扣题解/数组和哈希/数组/删除排序数组中的重复项.md
        - 加一: 500-力扣题解/数组和哈希/数组/加一.md
        - 加油站: 500-力扣题解/数组和哈希/数组/加油站.md
        - 只出现一次的数字: 500-力扣题解/数组和哈希/数组/只出现一次的数字.md
        - 存在重复元素: 500-力扣题解/数组和哈希/数组/存在重复元素.md
        - 旋转图像: 500-力扣题解/数组和哈希/数组/旋转图像.md
        - 旋转数组: 500-力扣题解/数组和哈希/数组/旋转数组.md
    - 树图和链表:
      - 图:
        - 克隆图: 500-力扣题解/树图和链表/图/克隆图.md
      - 树:
        - 二叉搜索树:
          - 二叉搜索树的最小绝对差: 500-力扣题解/树图和链表/树/二叉搜索树/二叉搜索树的最小绝对差.md
          - 二叉搜索树节点最小距离: 500-力扣题解/树图和链表/树/二叉搜索树/二叉搜索树节点最小距离.md
          - 二叉搜索树迭代器: 500-力扣题解/树图和链表/树/二叉搜索树/二叉搜索树迭代器.md
          - 最接近的二叉搜索树值: 500-力扣题解/树图和链表/树/二叉搜索树/最接近的二叉搜索树值.md
      - 链表:
        - 反转链表: 500-力扣题解/树图和链表/链表/010_反转链表.md
        - 反转链表II: 500-力扣题解/树图和链表/链表/011_反转链表II.md
        - 环形链表: 500-力扣题解/树图和链表/链表/020_环形链表.md
        - 环形链表II: 500-力扣题解/树图和链表/链表/021_环形链表II.md
        - 回文链表: 500-力扣题解/树图和链表/链表/030_回文链表.md
        - 排序链表: 500-力扣题解/树图和链表/链表/040_排序链表.md
        - 相交链表: 500-力扣题解/树图和链表/链表/050_相交链表.md
        - 旋转链表: 500-力扣题解/树图和链表/链表/060_旋转链表.md
        - 重排链表: 500-力扣题解/树图和链表/链表/070_重排链表.md
        - 两两交换链表中的节点: 500-力扣题解/树图和链表/链表/200_两两交换链表中的节点.md
        - 合并两个有序链表: 500-力扣题解/树图和链表/链表/201_合并两个有序链表.md
        - K个一组翻转链表: 500-力扣题解/树图和链表/链表/300_K个一组翻转链表.md
    - 求和:
      - 两数之和: 500-力扣题解/求和/001_两数之和.md
      - 两数之和Ⅱ: 500-力扣题解/求和/002_两数之和Ⅱ.md
      - 两数之和Ⅲ: 500-力扣题解/求和/003_两数之和Ⅲ.md
      - 两数之和Ⅳ: 500-力扣题解/求和/004_两数之和Ⅳ.md
      - 三数之和: 500-力扣题解/求和/100_三数之和.md
      - 四数之和: 500-力扣题解/求和/200_四数之和.md
    - 滑动窗口:
      - 包含两不同字符最长子串: 500-力扣题解/滑动窗口/包含两不同字符最长子串.md
      - 数据流的中位数: 500-力扣题解/滑动窗口/数据流的中位数.md
      - 最小覆盖子串: 500-力扣题解/滑动窗口/最小覆盖子串.md
      - 水果成篮: 500-力扣题解/滑动窗口/水果成篮.md
      - 滑动窗口中位数: 500-力扣题解/滑动窗口/滑动窗口中位数.md
      - 滑动窗口最大值: 500-力扣题解/滑动窗口/滑动窗口最大值.md
  - 代码库:
    - HelloWorld: 600-代码库/00-HelloWorld.md
    - Hash:
      - C语言哈希: 600-代码库/010_Hash/C语言哈希.md
      - Go实现简单HashMap: 600-代码库/010_Hash/Go实现简单HashMap.md
    - 堆栈:
      - 简单栈实现: 600-代码库/020_堆栈/简单栈实现.md
    - 文件操作:
      - python实现批量重命名: 600-代码库/200_文件操作/02-python实现批量重命名.md
    - 各种算法:
      - 排序算法: 600-代码库/300_各种算法/排序算法.md
      - 雪花算法: 600-代码库/300_各种算法/雪花算法.md
    - 数学素材:
      - 九九乘法表: 600-代码库/400_数学素材/01-九九乘法表.md
      - 打印100以内的素数: 600-代码库/400_数学素材/02-打印100以内的素数.md
      - 打印杨辉三角: 600-代码库/400_数学素材/03-打印杨辉三角.md
    - 机机通信人机交互:
      - 基于Beego的简单WEB服务: 600-代码库/500_机机通信人机交互/基于Beego的简单WEB服务.md
      - 实现简单的TCP通信: 600-代码库/500_机机通信人机交互/实现简单的TCP通信.md
    - 小游戏:
      - Python贪吃蛇: 600-代码库/800_小游戏/Python贪吃蛇.md
  - 百度: https://www.baidu.com
  - 评论: https://github.com/hemy08/hemynotes/issues
